server: 
  port: 8080
  servlet: 
    context-path: /BarcodeHandle

spring: 
  profiles: 
    active: dev
  servlet:
    multipart:
      max-file-size: 3000MB
      max-request-size: 3000MB

xiaojz: 
  downloadPath: /home/xiaojz/download/


